# Generated by Django 3.2.5 on 2022-05-10 01:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fichas_alumnos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAlumno',
            fields=[
                ('rut', models.CharField(help_text='El rut debe ser ingresado sin puntos y con guión.', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(\\d{1,2}(?:\\d{3}){2}-[\\dkK])$')], verbose_name='Rut alumno')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(choices=[('lista_espera', 'En lista de espera'), ('documentos_pendientes', 'Documentos pendientes'), ('curso_asignado', 'Curso asignado'), ('retirado', 'Retirado')], default='lista_espera', max_length=32)),
            ],
            options={
                'verbose_name': 'Ficha Alumno',
                'verbose_name_plural': 'Fichas Alumnos',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='BancoTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trabajo', models.FileField(max_length=500, upload_to=fichas_alumnos.models.trabajo_directory_path)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas_alumnos.fichaalumno')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BancoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FileField(max_length=500, upload_to=fichas_alumnos.models.documento_directory_path)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas_alumnos.fichaalumno')),
            ],
            options={
                'verbose_name': 'Banco documento',
                'verbose_name_plural': 'Banco documentos',
                'ordering': ['id'],
            },
        ),
    ]
