# Generated by Django 3.2.5 on 2022-05-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0002_avancealumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancealumno',
            name='fecha_edicion',
            field=models.DateField(auto_now=True),
        ),
    ]
