# Generated by Django 3.2.5 on 2022-05-06 03:58

from django.db import migrations, models
import fichas_alumnos.models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0002_alter_fichaalumno_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancodocumento',
            name='documento',
            field=models.FileField(max_length=500, upload_to=fichas_alumnos.models.alumno_directory_path),
        ),
    ]
