# Generated by Django 3.2.5 on 2022-05-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0003_alter_avancealumno_fecha_edicion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaalumno',
            options={'ordering': ['rut'], 'permissions': (('can_view_listado_fichas', 'Can view listado fichas alumnos'), ('can_view_ficha_completa', 'Can view ficha alumno completa')), 'verbose_name': 'Ficha Alumno', 'verbose_name_plural': 'Fichas Alumnos'},
        ),
    ]
