# Generated by Django 3.2.5 on 2022-05-10 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fichas_alumnos', '0004_alter_fichaalumno_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleApoderado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas_alumnos.fichaalumno')),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle Apoderado',
                'verbose_name_plural': 'Detalle Apoderados',
                'ordering': ['id'],
            },
        ),
    ]
