# Generated by Django 3.2.5 on 2022-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0005_detalleapoderado'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancealumno',
            name='modificado',
            field=models.BooleanField(default=False),
        ),
    ]
