# Generated by Django 3.2.5 on 2022-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0010_alter_fichaalumno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='certif_nacimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='consent_fonoaudiologia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='consent_vidasana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='direccion',
            field=models.CharField(default='No asignado', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='ficha_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='formulario_salud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='nombre_madre',
            field=models.CharField(default='No asignado', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='nombre_padre',
            field=models.CharField(default='No asignado', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='telefono',
            field=models.CharField(default='No asignado', max_length=255),
            preserve_default=False,
        ),
    ]
