# Generated by Django 3.2.5 on 2022-06-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0011_auto_20220530_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='anamnesis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fichaalumno',
            name='rut',
            field=models.CharField(help_text='El rut debe ser ingresado sin puntos y con guión.', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(\\d{1,3}(?:\\d{3}){2}-[\\dkK])$')], verbose_name='Rut alumno'),
        ),
    ]
