# Generated by Django 3.2.5 on 2022-07-27 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_alumnos', '0012_fichaalumno_anamnesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaalumno',
            name='rut',
            field=models.CharField(help_text='El rut debe ser ingresado sin puntos y con guión.', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^(\\d{1,3}(?:\\d{3}){2}-[\\dkK])$')], verbose_name='Rut alumno'),
        ),
    ]
