# Generated by Django 3.2.5 on 2022-05-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0007_curso_docente_jefe'),
        ('fichas_alumnos', '0009_alter_detalleapoderado_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fichas_alumnos.fichaalumno')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.nivel')),
            ],
            options={
                'verbose_name': 'Lista de espera',
                'verbose_name_plural': 'Lista de espera',
                'ordering': ['id'],
            },
        ),
    ]
