# Generated by Django 3.2.5 on 2022-05-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_espera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listaespera',
            options={'ordering': ['id'], 'permissions': (('can_avanzar_lista_espera', 'Puede avanzar lista de espera'),), 'verbose_name': 'Lista de espera', 'verbose_name_plural': 'Lista de espera'},
        ),
    ]
