# Generated by Django 3.2.5 on 2022-05-13 23:35

import cursos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('periodo', models.CharField(default=2022, max_length=4)),
                ('cupos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.CharField(max_length=250)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detalle docente',
                'verbose_name_plural': 'Detalle docentes',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.nivel'),
        ),
        migrations.CreateModel(
            name='CronogramaActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(max_length=500, upload_to=cursos.models.actividad_directory_path)),
                ('fecha_edicion', models.DateField(auto_now=True)),
                ('modificado', models.BooleanField(default=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cronograma actividad',
                'verbose_name_plural': 'Cronograma de actividades',
                'ordering': ['id'],
            },
        ),
    ]
