# Generated by Django 3.2.5 on 2022-05-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_cupos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id'], 'permissions': (('can_view_listado_cursos', 'Can view listado cursos'),), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
