# Generated by Django 3.2.5 on 2022-05-17 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='letra',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('([a-zA-Z])')]),
        ),
    ]
