# Generated by Django 3.2.5 on 2022-05-18 16:19

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramaactividad',
            name='imagen',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=cursos.models.actividad_directory_path),
        ),
    ]
