# Generated by Django 3.2.5 on 2022-05-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0005_alter_cronogramaactividad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledocente',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
