# Generated by Django 3.2.5 on 2022-05-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0006_alter_detalledocente_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docente_jefe',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Docente'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
