# Generated by Django 3.2.5 on 2022-07-27 16:12

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_docente_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaactividad',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=cursos.models.actividad_directory_path),
        ),
    ]
