# Generated by Django 3.2.5 on 2022-07-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_transfer_imagen_archivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronogramaactividad',
            name='imagen',
        ),
    ]
