# Generated by Django 3.2.5 on 2022-07-29 16:21

import cursos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_remove_cronogramaactividad_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoTrabajo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trabajo', models.FileField(max_length=500, upload_to=cursos.models.trabajo_directory_path)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Trabajo curso',
                'verbose_name_plural': 'Trabajos curso',
                'ordering': ['id'],
            },
        ),
    ]
